### ISSUE TITLE
The dmc vision (task=dmc_walker_walk) has very bad performance

### ISSUE THREAD

**Issue by LYK-love** [chandar-lab/Recall2Imagine#11]
Hello, I ran R2I with command:
```sh
current_date=$(date "+%Y%m%d-%H%M%S")
python recall2imagine/train.py \
    --configs dmc_vision \
    --ssm_type mimo \
    --wdb_name  dmc_original_${current_date} \
    --logdir ./logs/dmc_original_${current_date}
```
and got very low scores. According to DreamerV3 paper, it can achieve score > 900.
<img width="954" alt="image" src="https://github.com/chandar-lab/Recall2Imagine/assets/74082944/bff244f2-a37a-4144-816e-b04d3749d13a">

However, R2I can only achieve score < 200.
<img width="636" alt="image" src="https://github.com/chandar-lab/Recall2Imagine/assets/74082944/a1b1ebda-6baf-4783-9d83-311b27e9694e">

I think the hyperparameters are the same, in R2I's `config.yaml`, I saw
```yaml
run.train_ratio: 512
  run.steps: 1e6
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
```
, this aligns with DreamerV3:
<img width="1061" alt="image" src="https://github.com/chandar-lab/Recall2Imagine/assets/74082944/2f30c592-c2b7-421b-baf5-2dfda6e8eb22">

Can you explain why this happens? Maybe it's because the ssm backbone is not so good as gru in this task? Or there's sth wrong with my hyperparameters?

**Comment by artemZholus** [comment]
This looks like a serious issue. I will take a look.

**Comment by artemZholus** [comment]
Hi @LYK-love ,

after a quick search I found that the most likely reason is the mismatch of SSM hyperparameters. For example, you are probably using the hidden size of 128 in each layer of SSM. This is not too small (we used 512 in the paper if I remember correctly). There can be other mismatches too. I will be doing some reproducibility checks in the next few days and then get back to you. You can ask me anything here in the meantime.

**Comment by artemZholus** [comment]
Please note that the hidden size alone does not guarantee to fix everything, but you can try that in the meantime.

**Comment by LYK-love** [comment]
I see the hidden_size attribute in the config file:
```yaml
rssm: {deter: 4096, units: 1024, hidden: 128, stoch: 32, classes: 32,  ... }
```
Here you set `hidden` to be 128. I also see that in `mmaze` env, you set it to be `512`:
```yaml
mmaze:
  task: gym_memory_maze:MemoryMaze-9x9-v0
  ... 
  rssm.deter: 2048
  rssm.units: 1024
  .*\.cnn_depth: 48
  .*\.mlp_units: 400
  .*\.layers: 4
  .*\.mlp_layers: 4
  ssm.n_layers: 5
  rssm.hidden: 512
```
In this sense, hidden size=512 should reproduce the score for mmaze.  

Now I am trying to know if R2I can achieve original DreamerV3's performance with GRU. It should work since you didn't change the architecture except the backbone. My command is:

```sh
current_date=$(date "+%Y%m%d-%H%M%S")
python recall2imagine/train.py \
    --configs dmc_vision \
    --ssm_type gru \
    --wdb_name  dmc_original_${current_date} \
    --logdir ./logs/dmc_original_${current_date}
```
Can you tell me what should I do in further to get the DreamerV3 score (with GRU backbone) on your code base? One thing worth consideration, as you mentioned, is the hidden size, since in DreamerV3, we have
```yaml
rssm: {deter: 4096, units: 1024, stoch: 32, classes: 32, ... }
```
, and there is no hidden size attribute here.
